import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#002d74",
        "on-secondary-fixed": "#00174b",
        "error": "#ba1a1a",
        "on-surface-variant": "#444651",
        "on-error-container": "#93000a",
        "tertiary-container": "#5e1b02",
        "on-tertiary-fixed-variant": "#7a2f14",
        "surface-dim": "#dad9e0",
        "surface-tint": "#3d5ca4",
        "background": "#faf8ff",
        "surface-bright": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0f7",
        "on-tertiary-container": "#e27f5d",
        "on-secondary-container": "#fefcff",
        "on-background": "#1a1b20",
        "on-primary-fixed-variant": "#22438a",
        "inverse-surface": "#2f3035",
        "surface-container": "#eeedf4",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e7ee",
        "secondary-fixed": "#dbe1ff",
        "on-secondary": "#ffffff",
        "tertiary": "#3b0d00",
        "surface": "#faf8ff",
        "tertiary-fixed": "#ffdbd0",
        "on-primary": "#ffffff",
        "secondary-container": "#316bf3",
        "inverse-primary": "#b1c5ff",
        "outline": "#747782",
        "on-surface": "#1a1b20",
        "primary-fixed": "#dae2ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#001947",
        "surface-container-low": "#f4f3fa",
        "primary-fixed-dim": "#b1c5ff",
        "surface-variant": "#e3e2e8",
        "on-tertiary-fixed": "#390c00",
        "surface-container-highest": "#e3e2e8",
        "secondary": "#0051d5",
        "primary": "#001a49",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-container": "#7a98e4",
        "secondary-fixed-dim": "#b4c5ff",
        "outline-variant": "#c4c6d2"
      },
      spacing: {
        "sidebar-width": "260px",
        "container-padding": "24px",
        "grid-gutter": "20px",
        "base": "4px",
        "sm": "8px",
        "lg": "24px",
        "xl": "32px",
        "xs": "4px",
        "md": "16px",
        "base-unit": "4px",
        "gutter-card": "12px",
        "margin-page": "16px",
        "padding-element": "16px",
        "stack-gap": "8px"
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        "label-caps": ["var(--font-manrope)"],
        "body-main": ["var(--font-manrope)"],
        "display-time": ["var(--font-manrope)"],
        "heading-md": ["var(--font-manrope)"],
        "status-text": ["var(--font-manrope)"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "h3": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "h2": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "h1": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "stat-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "body-main": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-time": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "heading-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "status-text": ["13px", { "lineHeight": "18px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
};

export default config;
